Develope/fix request urls
MadAppGang/identifo-admin pull request #18
Opened 2021-02-15 13:18 UTC by nikita-ks

2021-02-15 21:12 UTC, Compaurum approved these changes

2021-02-16 10:22 UTC, SuddenGunter approved these changes

2021-02-17 07:04 UTC, erudenko requested changes

2021-02-17 07:04 UTC, erudenko commented on src/utils/environment.js
> +export const ENV = {
for future reference, `utils` is an indication of bad architecture decisions. Like big trash for the code that not fit in the app structure.

2021-02-17 07:04 UTC, erudenko commented on src/services/Account/account.js
> +import { ENV } from '~/utils/environment';
I am not sure it is a good bane for the service
This service provide some settings data, we already have settings provider here. Why not move it there?

2021-02-19 10:21 UTC, SuddenGunter approved these changes

2021-02-19 12:03 UTC, merged